# Generated by Django 5.2.6 on 2025-09-26 16:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('time_start', models.TimeField()),
                ('ticket_link', models.URLField(blank=True)),
                ('cfp_link', models.URLField(blank=True)),
                ('sponsor_link', models.URLField(blank=True)),
                ('location_main', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=255)),
                ('location_link', models.URLField(blank=True)),
                ('keynote_title', models.CharField(max_length=255)),
                ('keynote_subtitle', models.CharField(blank=True, max_length=255)),
                ('speaker_title', models.CharField(max_length=255)),
                ('speaker_subtitle', models.CharField(blank=True, max_length=255)),
                ('schedule_title', models.CharField(max_length=255)),
                ('schedule_subtitle', models.CharField(blank=True, max_length=255)),
                ('sponsor_title', models.CharField(max_length=255)),
                ('sponsor_subtitle', models.CharField(blank=True, max_length=255)),
                ('banner_title', models.CharField(blank=True, max_length=255)),
                ('banner_call_to_action', models.CharField(blank=True, max_length=255)),
                ('banner_link', models.URLField(blank=True)),
                ('location_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('call_to_action', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(default='00:00')),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(default='23:59')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='home.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.RichTextField()),
                ('image_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=32)),
                ('is_subcontent', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
